### ISSUE TITLE
Using remark-twemoji with gatsby mdx

### ISSUE THREAD

**Issue by LeptoFlare** [madiodio/remark-twemoji#9]
I'm trying to use this plugin with `gatsby-plugin-mdx`
Here's what tha portion of the `gatsby-config.js` looks like:
```js
    {
      resolve: `gatsby-plugin-mdx`,
      options: {
        extensions: [`.mdx`, `.md`],
        defaultLayouts: {
          default: path.resolve("src/templates/md.js"),
          posts: path.resolve("src/templates/post.js"),
        },
        gatsbyRemarkPlugins: [
          `gatsby-remark-images`,
          `gatsby-remark-prismjs`,
        ],
        remarkPlugins: [require(`remark-twemoji`)],
      },
    },
```

And... well it works... sorta.
![image](https://user-images.githubusercontent.com/47790183/87076487-d8fc9d80-c1ef-11ea-9a6f-d642dabd0b49.png)

The images are far too large for the size of the text.
For some extra context, here's what a pseudo paragraph looks like:
![image](https://user-images.githubusercontent.com/47790183/87076723-20832980-c1f0-11ea-8b70-2f8501e04293.png)

**Comment by madiodio** [comment]
Hey @LeptoFlare, thanks for opening this.

This is actually solved by targeting the class `.emoji` applied to the img tag used to display the emoji. You can obviously change the class in the options like mentioned [here](https://github.com/madiodio/remark-twemoji#other-options). You now just have to add somewhere in your app this piece of CSS like it is shown [here](https://github.com/twitter/twemoji#inline-styles):

```css
img.emoji {
   height: 1em;
   width: 1em;
   margin: 0 .05em 0 .1em;
   vertical-align: -0.1em;
}
```

Adding the above should work for you. Let me know if it does.

**Comment by LeptoFlare** [comment]
I see, however, I feel this should be on by default.

I don't think people should be required to add extra CSS just to use the plugin

**Comment by madiodio** [comment]
I hear you, this might be a slight inconvenience. But I believe you'll have to write some CSS at some point if you want to use this plugin anyway, won't you? 

We can inject inline styles automatically to the img tag but that isn't performant at scale and will bring the same inconvenience to those already using this and want to fine-tune their styles.

So I'm going to close this but feel free to fork and accommodate it to your needs, it's open source after all 😅.
